### ISSUE TITLE
CI: retargeting a stacked PR to main runs no checks at all — pull_request has no types:, so 'edited' is not in the default set

### ISSUE THREAD

**Issue by joeleaver** [joeleaver/rinch#448]
Found the hard way while merging the #252 focus stack.

## The trap

`.github/workflows/ci.yml`'s trigger is:

```yaml
on:
  pull_request:
    branches: [main]
```

With no `types:`, GitHub applies the default **`[opened, synchronize, reopened]`**. Changing a PR's base branch fires **`edited`**, which is not in that set.

**Consequence: a stacked PR that is retargeted to `main` — whether automatically when its parent merges, or manually via the API — gets no CI run at all.** It sits showing "no checks", which reads identically to "checks haven't started yet", and it can be merged in that state.

## Confirmed empirically, not just from the docs

PR #432 was auto-retargeted from `fix/316-blurred-caret` to `main` ten seconds after its parent merged. Nine minutes later:

- `repos/joeleaver/rinch/commits/d95c7ebd/check-runs` → **empty**
- `gh api actions/runs?branch=fix/312-data-nofocus` → **zero runs, ever**

Ruled out as explanations: queued runs = 0, in-progress = 7 (so the queue was moving), and `ci.yml` has no `concurrency:` group — only `docs.yml` does, keyed by ref for Pages.

## Why it matters more than it looks

This is how an unverified change reaches `main`. In our case #432 carried `crates/rinch-web/tests/nofocus.rs`, which is `#![cfg(target_arch = "wasm32")]` — so it is skipped silently by every native run and had **never executed anywhere**. The `test-wasm` job is the only thing that would run it, and the retarget is exactly the moment we were relying on to make that happen.

It compounds with a second gotcha already known here: `gh pr checks` prints `no checks` in this situation, and every naive waiter (`until ! gh pr checks N | grep -q pending`) treats the absence of "pending" as success. So the tooling actively reports a PR with zero CI as ready.

## Workarounds that do work

- A **force-push after a rebase** is a `synchronize` — this is the natural one for a stacked PR, which usually needs rebasing onto the squashed parent anyway.
- `git commit --allow-empty` then push — also `synchronize`. Adds a no-op commit that a squash-merge discards.
- Close and immediately reopen the PR — `reopened` is in the default set. **Only safe when the base branch still exists**; if the base was deleted, the PR is permanently un-reopenable (this repo has hit that twice: #74 and #54).

## The fix, and the trade-off — not obviously worth taking

Adding `edited` to `types:`:

```yaml
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited]
```

would make retargets trigger CI — but `edited` **also fires on every title and body edit**, and this campaign edits PR bodies routinely (`gh api -X PATCH .../pulls/N`). That would mean a full matrix run, including the ~9-minute `build` job, every time someone fixes a typo in a PR description.

Options worth weighing:

1. **Leave the trigger alone and document it.** Cheapest. Put it in CLAUDE.md next to the existing CI notes so the next person doing a stacked pair knows to force-push.
2. **Add `edited` and accept the noise.** Correct-by-construction; costs CI minutes on body edits.
3. **Add `edited` plus a job-level guard** that skips when only the title/body changed — `github.event.changes.base` is present exactly when the base changed, so `if: github.event.action != 'edited' || github.event.changes.base` gives the retarget run without the typo runs. Slightly fiddly, but it is the option that actually fits what we want.

I lean toward (3), with (1) as the minimum acceptable outcome — the current state is a silent hole, and "no checks" being indistinguishable from "not started" is the part that makes it dangerous.

Whatever is chosen, the CLAUDE.md note is worth having either way.

**Comment by joeleaver** [comment]
## A second instance of the same class, confirmed empirically: `gh run rerun` does not recompute the merge ref either

The issue above covers a **retarget** producing no CI run. There is a sibling case with the same root shape — *the base moved and CI did not notice* — and the obvious remedy for it does not work.

**Setup.** `main` was broken by a missing struct field (#449) and fixed by #451, merged at ~17:23. PR #432's CI run `33660398294` had been created at **17:19:55**, i.e. against the broken base, and its `clippy` / `clippy-wasm` jobs failed with the two `error[E0063]` lines.

**What was tried.** `gh run rerun 33660398294 --failed`, on the reasonable assumption that a re-run would rebuild against the current base.

**What happened.** It re-ran the jobs *inside the existing run*, which is pinned to the merge ref computed when the run was created. The jobs failed again for the same reason. `gh run list --branch fix/312-data-nofocus` still showed exactly **one** CI run — no new one was created. A `build` job passing at 9m51s in that same run is not evidence to the contrary; every job in a run shares the base the run was created with.

Also worth knowing: on a second PR, `gh run rerun <id> --failed` refused outright with *"cannot be rerun; its workflow file may be broken"*, which is a confusing message for a workflow that is fine.

**So the only reliable way to get CI against a moved base is to push** — an empty commit (`git commit --allow-empty`) or any real commit, both of which are `synchronize`. A force-push after a rebase counts too, which is convenient when a stacked PR needs rebasing anyway.

**Why this compounds the original issue.** Both failure modes present as *the PR's fault*:

- after a retarget: **no checks at all**, which `gh pr checks` prints as `no checks` — indistinguishable from "not started yet";
- after a base fix: **a stale red**, which reads as a defect in the PR rather than in the base it was built against.

Neither is self-correcting, and in a session merging many PRs the second one is the more dangerous, because a red that is *someone else's* invites either an unnecessary investigation or — worse — a habit of merging past reds.

**Practical rule until this is fixed:** after `main` moves in a way that could affect a PR (a base fix, a squash-merge of its parent), **push to the branch**; do not rerun, and do not read the existing result as current. Whatever option is chosen from the three above, this belongs in the CLAUDE.md CI note alongside it.

**Comment by joeleaver** [comment]
## A second, more common route to the same silent no-CI state: a PR with merge conflicts gets **zero** workflow runs

Hit this twice tonight (#481 and #472) and confirmed the mechanism both times.

**When a PR is `CONFLICTING` (`mergeStateStatus: DIRTY`), GitHub cannot compute the merge commit that a `pull_request` workflow runs against, so it creates no run at all.** Not a failed run — *no run*. `gh pr checks N` answers:

```
no checks reported on the 'branch-name' branch
```

which reads as "nothing wrong here" rather than "this was never tested".

Confirmed by construction: on #472, a push at 23:39 produced no run for 6+ minutes; `gh pr view 472 --json mergeable,mergeStateStatus` gave `CONFLICTING`/`DIRTY`; after merging main in and resolving one conflict, **CI fired within 25 seconds of the push**. Same sequence on #481 — no runs at all until it was rebased onto current main, then a full set immediately.

## Why this is worse than the retargeting case in the title

The retarget case needs someone to retarget. **This one happens by itself**, to any PR that sits while `main` moves — which, on a night when nine PRs merge, is every PR in the queue. And it produces the most dangerous possible signal: a green-looking absence.

Both routes share one root hazard: **absence of checks is indistinguishable from checks that passed, in the UI and in `gh`.** Whatever the fix for the `types:` half, it should be paired with something that makes "never ran" visible — a required check that fails closed, or a status posted when no run exists.

## Practical rule until then

**Never read "no checks reported" as a pass.** Before trusting any PR's CI, confirm a run actually exists *and* postdates the tip of `main`:

```
gh api "repos/joeleaver/rinch/actions/runs?branch=<branch>&per_page=1" \
  -q '.workflow_runs[0] | "\(.created_at) \(.status)/\(.conclusion)"'
gh pr view <N> --json mergeable,mergeStateStatus
```

This pairs with the existing mechanical staleness rule (*any PR whose newest CI run predates main's tip is unverified by definition*) — a conflicting PR is the degenerate case where the newest run predates the tip **and will never be replaced** until someone resolves the conflict.
